export const rowData = [
  {
    Id: 1,
    Name: 'Konstantin',
    Age: '40',
    Email: 'kostya.zhirnov@gmail.com',
    Gender: 'Male',
    DOB: '1982-06-11',
    Country: 'Russia',
    City: 'Murmansk',
  },
  {
    Id: 2,
    Name: 'Olga',
    Age: '34',
    Email: 'olga@gmail.com',
    Gender: 'Female',
    DOB: '1989-02-22',
    Country: 'Ukraina',
    City: 'Vinnica',
  },
  {
    Id: 3,
    Name: 'Sava',
    Age: '14',
    Email: 'savelii@gmail.com',
    Gender: 'Male',
    DOB: '2008-09-20',
    Country: 'Russia',
    City: 'Severodvinsk',
  },
  {
    Id: 4,
    Name: 'Anastasiia',
    Age: '3',
    Email: 'anastasiia@gmail.com',
    Gender: 'Female',
    DOB: '2020-03-13',
    Country: 'Russia',
    City: 'St. Petersburg',
  },
]
